# rec server
server.port=13579
server.pushService=pushRedisService

# redis
redis.hostName=127.0.0.1
redis.port=6380
redis.timeout=3000
redis.maxTotal=8
redis.maxWaitMillis=1000
redis.testOnBorrow=true

# elasticsearch
es.host=127.0.0.1
es.port=9200
es.user=elastic
es.password=openrec-es-password

# rank engine
rank.open=false

