spring.profiles.active=standalone
serving.graph.item-file=${ITEM_GRAPH_FILE:item_graph.json}
serving.graph.user-file=${USER_GRAPH_FILE:user_graph.json}
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.show-details=never
management.metrics.tags.application=rec-server
server.error.include-message=always
